include:
  - ./todo-backend/docker-compose.yml
  - ./todo-frontend/docker-compose.yml

services:
  proxy:
    image: nginx:alpine-slim
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    container_name: reverse-proxy
    depends_on:
      - server
      - app
