services:
  app:
    image: todo-frontend:dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - "5173:5173"
    container_name: todo-frontend-dev
    environment:
      - VITE_BACKEND_URL=/api
  debug-helper:
    image: busybox
    container_name: debug-helper