services:
  server:
    image: todo-backend
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-backend
    environment:
      NODE_ENV: production
      MONGO_URL: mongodb://the_username:the_password@mongo:27017/the_database
      REDIS_URL: redis://redis:6379
    depends_on:
      - mongo
      - redis
  mongo:
    image: docker.io/library/mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
  redis:
    image: docker.io/library/redis:8.6.1-alpine
    command: [ 'redis-server', '--appendonly', 'yes' ]
    volumes:
      - redis_data:/data
volumes:
  redis_data:
